### ISSUE TITLE
Truncate long fields in the table view

### ISSUE THREAD

**Issue by fsproru** [commandeer/open#102]
cc @ssanri

**Comment by bwship** [comment]
@ssanri - was goin got do this as where there is an Object in the column, then show some message there and have a show_hide toggle on the top of the page for it.

**Comment by ssanri** [comment]
when we were looking at it with @fsproru it made more sense to stringify large json objects in columns and show certain amount in field with ellipsis to avoid huge row heights. Also attach to Format toggle so when formatting is disabled it will be like this. Is that makes sense?

**Comment by bwship** [comment]
@ssanri - this is what I have going now.  if format data is on, it will hide objects and arrays, and truncate 20 characters with ellipsis.  Let me know what you think.

<img width="1282" alt="object1" src="https://user-images.githubusercontent.com/1326114/102523560-b48dd280-4065-11eb-8195-a790287e049a.png">

<img width="1283" alt="object2" src="https://user-images.githubusercontent.com/1326114/102523565-b6f02c80-4065-11eb-8bf3-032207632ee6.png">

**Comment by bwship** [comment]
@ssanri - Let me try it with the stringify, that might be pretty helpful

**Comment by bwship** [comment]
@ssanri - yea I like this where it previews it

<img width="1299" alt="object3" src="https://user-images.githubusercontent.com/1326114/102525355-2535ee80-4068-11eb-9799-8c53d44f46db.png">

**Comment by ssanri** [comment]
yes! so much better. Especially in your first screenshot json data was still not that big. if you think it is an array of 100 deeply nested object in one column, other columns in same row are set to vertical center, so it makes it difficult to find the center time to time if you have bunch of large json fields in different sizes. But loved this solution.

**Comment by bwship** [comment]
Released in version 1.6
