### ISSUE TITLE
Customize DynamoDB port

### ISSUE THREAD

**Issue by ssanri** [commandeer/open#108]
@fsproru I was testing something tonight and noticed we are no longer able to customize port that dynamodb uses. Maybe I am not remembering correctly but switching between localstack predefined ports to custom ports would be really helpful. Uses cases might be using different port in env variables of localstack because of 4566 ( edge port ) or old 4569 is being used or switching between dynamodb-local and localstack containers.

Please let me know if you have any questions or feature is already there but I can't find it. 

thanks.

**Comment by fsproru** [comment]
@ssanri that actually an interesting topic of discussion.

Are you using both dynamodb-local (which is different from LocalStack) and LocalStack?

The way to specify a different port DynamoDB connects to in the current version is creating multiple local accounts in commandeer with different LocalStack urls.

**Comment by ssanri** [comment]
Yes, I was actually doing a performance analysis on how localstack dynamodb and dynamodb-local handles big data but in account settings I couldn't see any place to change the dynamodb port.

**Comment by fsproru** [comment]
Now that LocalStack uses a single port, we use LocalStack URL from LocalStack settings for local accounts for all services including DynamoDB. That said once we were implementing it, I had the same thought that we may still need the ability to customize the endpoint url per AWS service. And it looks like this is a usecase for it. For example, you tested dynamodb-local and localstack on the same machine.

We'll bring the ability to specify the endpoint URL per AWS service back then, good call!

**Comment by bwship** [comment]
You can now adjust these in the LocalStack settings

**Comment by fsproru** [comment]
@ssanri we just released the version 1.6 which has the ability to customize AWS endpoints from LocalStack settings. You can also do it from AWS settings too. Let us know if you run into any issues.
