### ISSUE TITLE
Persisting Data

### ISSUE THREAD

**Issue by shawnemullen** [commandeer/open#109]
I set DATA_DIR in localstack environment variables, but none of my data is persisted between sessions.  I also set HOST_TMP_FOLDER.  What am I missing?

**Comment by fsproru** [comment]
Hi @shawnemullen, are you using the latest version of Commandeer 1.5.2?

We had an issue with environment variables not passing to the LocalStack container that was fixed in 1.5.2.

**Comment by bwship** [comment]
Closing this as I believe it is solved.
