### ISSUE TITLE
How to delete comandeer account

### ISSUE THREAD

**Issue by kapi-ai** [commandeer/open#110]
Hi,
I made an account, but comandeer is not for me so now I want to delete it. How can I do that? I did not find a button in my account settings or something related to it in the docs.

**Comment by fsproru** [comment]
Hi @kapi-ai, no worries, most of your account data is stored locally. You can just delete your data folder which you can access from the help menu in top right of Commandeer desktop app. As long as you deleted your data from you computer and deleted the app you should be all set.

Let us know if you have any issues. Also, we're constantly improving the app experience and would love to hear why Commandeer didn't work for you. Feel free to leave a comment here on why or send us you feedback privately in the email at contact@getcommandeer.com

**Comment by fsproru** [comment]
Closing it, @kapi-ai let us know if you run into any issues.
