### ISSUE TITLE
Serverless Runner shows no output when running

### ISSUE THREAD

**Issue by fsproru** [commandeer/open#117]
cc: @PeteCion08534

**Comment by nelsben** [comment]
Hello, I've been having the same problem over the past couple of days as well. I've tried using the serverless.yml files  provided in a couple of the sample projects, but the serverless runner appears to be hung. These serverless.yml files run fine form command line.

![image](https://user-images.githubusercontent.com/49027024/105866980-90a5a100-5fc2-11eb-9721-e9add3acbcf1.png)

**Comment by fsproru** [comment]
@nelsben @PeteCion08534, this is fixed in the release 1.6.3. Let us know if you run into anything on the new version.
