### ISSUE TITLE
Serverless Runner Not Providing Output/Hanging

### ISSUE THREAD

**Issue by nelsben** [commandeer/open#118]
Serverless runner does not provide output when running, and the process appears to hang indeffinetly. I tested with both commandeer example serverless.yml files, and my own custom ones. The serverless.yml files are compilable when run from command line. I am on a windows 10 64 bit OS.

![image](https://user-images.githubusercontent.com/49027024/105871426-47a41b80-5fc7-11eb-9969-9a7c9a8c825a.png)

All jobs are hung as processing.
![image](https://user-images.githubusercontent.com/49027024/105871554-6b676180-5fc7-11eb-8f0a-8a6b540c5dea.png)

**Comment by fsproru** [comment]
@nelsben thanks the info, we're working on a patch release to get it out quick.

**Comment by nelsben** [comment]
@fsproru thanks. Any idea on an eta?

**Comment by fsproru** [comment]
The fix is in testing, 1.6.3 should go out in the next day.

**Comment by fsproru** [comment]
@nelsben 1.6.3 with the fix is released. Let us know if you run into any issues.
