### ISSUE TITLE
S3: Delete button clunky or not working

### ISSUE THREAD

**Issue by GimignanoF** [commandeer/open#12]
As the tile says, when i press the Delete button to delete a bucket or a file from a bucket in a local S3 server it doesn't work or you have to press it multiple times before the file is actually deleted (i tried with the bucket but after pressing the delete button like 50 times the bucket was still there) :/

Steps to reproduce:

* Run localstack on your machine
* Open Commandeer and go to the S3 tab
* Make sure you are "connected" to your local account, wich is the localstack account
* Click on a bucket or on a file and hit the delete button on the right

**Comment by fsproru** [comment]
Hi @GimignanoF, thanks for reporting it, we'll take care of it in one of our next releases.

**Comment by fsproru** [comment]
Hey @GimignanoF, we just released Commandeer 0.3.0 which has a non-empty folder deletion feature implemented. You can delete a non-empty bucket now too.

Here are the release notes: https://getcommandeer.com/docs/releases/version-0_3_0

Let us know if you see any more issues.
