### ISSUE TITLE
Asked to Go Through First Launch Tour Everytime

### ISSUE THREAD

**Issue by ssnyder-sme** [commandeer/open#165]
I'm asked to go through the first launch tour everytime I open the application. Whether I skip the tour, or click next and exhaust the list of items to explain, the next time I open the app, it presents the tour again.

I'm on a mackbook pro (OS 10.15.7)

<img width="1509" alt="Screen Shot 2021-03-09 at 5 27 37 PM" src="https://user-images.githubusercontent.com/69162122/110561599-d34bb480-80fc-11eb-874a-cfb36b1a7d71.png">

**Comment by bwship** [comment]
@ssnyder-sme - That is strange.  I have seen that on dev builds before but never in the prod build.  If you click the top right ? help icon in the app, and then click the data path folder, it will open up finder. in there, if you go to the users folder and open settings.json you will see a variable called hasSeenOnboarding.  If you set that to true, it will not show up next time.  We will investigate further why it is happening though.

**Comment by bwship** [comment]
This doesn't solve it.  But there will now be a toggle for this on the settings tab also.

<img width="887" alt="onboarding-tour" src="https://user-images.githubusercontent.com/1326114/110573641-9b0e9b00-8129-11eb-949c-3d9a5db2fef1.png">
