### ISSUE TITLE
Endlessly Refreshing Data

### ISSUE THREAD

**Issue by ssnyder-sme** [commandeer/open#167]
I can add one AWS account successfully and see all resources I expect (s3/api gateway/lambda), but adding a second one usually causes the app to refresh endlessly. I've deleted the app and the data folder and reinstalled, but still see this same behavior. 
<img width="847" alt="Screen Shot 2021-03-09 at 5 42 41 PM" src="https://user-images.githubusercontent.com/69162122/110649967-f8790b00-816e-11eb-811c-0ecf2fbd9eaa.png">

When I delete that account, it stops refreshing. I'll add a different AWS account, which will sometimes complete the refresh process, but I don't see all of the resources I expect. I've tried hitting the "Clear Local Cache" button, and also clicking the "Refresh Accounts" button, but still not seeing the resources I expect. 

For instance, using the aws cli with the set of credentials I used in Commandeer, i see 17 S3 buckets, but zero in Commandeer. I've also tried right clicking directly on the S3 nav item to refresh it, but i get this error message: "Error refreshing.Cannot asssign a read only property 'message of object "
![Screen Shot 2021-03-10 at 7 10 25 AM](https://user-images.githubusercontent.com/69162122/110650924-d2a03600-816f-11eb-8361-8aba3fe2a663.png)

But, I expect to see 50+ lambda functions, and when I right click on the Lambda nav item to refresh it, i don't see any error or any activity, but zero functions are found. 

If I go back to edit the account settings, and try to test the S3 connection, it says "Connection Failed"
![Screen Shot 2021-03-10 at 7 13 48 AM](https://user-images.githubusercontent.com/69162122/110651439-4c382400-8170-11eb-979c-3fd7b6f0d500.png)
Other accounts I've setup work when testing the S3 connection when I'm on the edit account credential screen.

This is on a Macbook pro, version 1.7.2 of the application, running Mac OS 10.15.7

**Comment by bwship** [comment]
So, I am adding in a more descriptive error in the toast, rather than Connection Failed.  You don't need to hit test connection.  I am still trying to track down if there are any issues in the actual component itself.  But now the actual error coming back from AWS will show up in the toast.

**Comment by ssnyder-sme** [comment]
How do you push out updates to the application? Do I need to re-download the app from the web console or does it auto update?

**Comment by ssnyder-sme** [comment]
Got the latest version 1.8.0 and when checking the s3 connection, it says "Cannot assign to read only property 'message' of object"
![Screen Shot 2021-03-23 at 6 13 34 PM](https://user-images.githubusercontent.com/69162122/112239315-80492580-8c03-11eb-97b9-37a6765003e5.png)

**Comment by bwship** [comment]
> How do you push out updates to the application? Do I need to re-download the app from the web console or does it auto update?

It is auto updated.  So you should see a notification that it will install when you restart the app.  You can check which version you are on by pressing the top right help icon in the app.

**Comment by bwship** [comment]
Is that error you are seeing when you press the Test Connection button in the account page?

**Comment by ssnyder-sme** [comment]
Hmm, I wasn't seeing any notification when opening the app. I was only able to get the latest version by downloading it from the web account page. Maybe I missed it.

Yup, I see that error when I press the Test Connection button in the account page. I was sorta thinking it might have been due to some limitations of the trial account, i.e. not being able to track enough resources, but I'm out of trial now and it's still happening. Even on one of the accounts that is able to test that s3 connection, I don't see all the ECS clusters; I see 3 out of the total 4 I know are in the account.

**Comment by ssnyder-sme** [comment]
Tried deleting the account and re-adding it. Upon re-adding I can test the s3 connection successfully, but i'm back at the endless refreshing state. I do see some additional resources than previously though....can see dynamo tables but still no lambdas

**Comment by bwship** [comment]
Are you certain that your keys have access to Lambda?  Did you press the refresh button that is directly on the Lambda page as well?

**Comment by ssnyder-sme** [comment]
100% certain, I use these credentials daily. Can list/invoke functions right now from the console and cli.

Tried a refresh button at the very top, and right clicking on Lambda in the navigation and refreshing there too. But right, it's just stuck endlessly refreshing: 
![Uploading Screen Shot 2021-03-24 at 8.25.37 AM.png…]()

**Comment by bwship** [comment]
In the side navigation, go to Commandeer -> System Logs and let's see if there are any hints there.  Once on that page, you can do a cmd + R to refresh the app, then lets see if there are any error logs there.  The actual refresh of all system data happens in a multi-process node call.  So if one of the refreshes fails they all should not, but it seems like something in there might be hosing it.

**Comment by ssnyder-sme** [comment]
Oh man, bunch of errors....can't seem to find node or sls. I'm using zsh and looks like it might be using sh?
![Screen Shot 2021-03-24 at 10 21 17 AM](https://user-images.githubusercontent.com/69162122/112355222-af56aa00-8c8a-11eb-9471-8edfe286aa34.png)

**Comment by bwship** [comment]
Hmm, those should not be related to the refresh though.  In the top right help menu, click on the data path link top opne up the finder window, and then delete the /services-cache folder, and in the app hit the refresh button one more time, to see if maybe this is an issue with the local cache.

**Comment by ssnyder-sme** [comment]
Deleted local cache. Tried again and it still endless refreshes. Nothing obvious in the system logs. This is pretty much blocking for me to use the app.

**Comment by bwship** [comment]
This should finally be fixed in 1.8.1.  Sorry for the delay, we had a heck of a time tracking down this issue.
