### ISSUE TITLE
Toggling "Connected to Lambda" on DynamoDB System Diagram Displays Error

### ISSUE THREAD

**Issue by ssnyder-sme** [commandeer/open#169]
When toggling the "Connected to Lambda" switch on the DynamoDB System Diagram displays an error about trying upper case an undefined variable.
![Screen Shot 2021-04-13 at 8 35 15 AM](https://user-images.githubusercontent.com/69162122/114580056-62377980-9c33-11eb-8f62-1add99ae1047.png)

**Comment by bwship** [comment]
this is the same issue as the refresh button.  Going to close this for now as it will go out with version 1.9.

**Comment by ssnyder-sme** [comment]
Thanks!
