### ISSUE TITLE
Dynamodb Stream Disabled but shows Enabled in Commandeer and Warns Me About it

### ISSUE THREAD

**Issue by ssnyder-sme** [commandeer/open#174]
I was alerted that some Dynamodb tables had streams enabled, but no stream defined, which was fantastic. But, i took steps to remediate that situation to remove the streams. I did that work a few days ago, but Commandeer still tells me that streams are enabled without a connected Lambda. Clicked refresh on the accounts but no change.

![Screen Shot 2021-04-22 at 5 37 44 PM](https://user-images.githubusercontent.com/69162122/115801443-9fb5a880-a391-11eb-8e51-a8e6d81fbdfb.png)
![Screen Shot 2021-04-22 at 5 36 34 PM](https://user-images.githubusercontent.com/69162122/115801455-a6dcb680-a391-11eb-95fe-a21056646cdc.png)

**Comment by ssnyder-sme** [comment]
Hmm, maybe just caching. Did a right click on the left hand nav Dynamodb element and refreshed tables, and was able to see the current state of the tables' streams reflected. So, was able to finally see this change reflected in Commandeer, but took a few refreshes...

**Comment by bwship** [comment]
@ssnyder-sme - I added an extra check in the code.  That if we see that a DynamoDB Stream is not enabled, then we do a hard refresh of the cache on the dynamodb tables to first validate if it is still disconnected.  This will go out in version 1.9 as well.

**Comment by ssnyder-sme** [comment]
Thank you!
