### ISSUE TITLE
Unable to refresh Dynamodb System Diagram

### ISSUE THREAD

**Issue by ssnyder-sme** [commandeer/open#175]
When clicking on the refresh button on the System Diagram tool, I get an error that "error_retrievingCannot read property 'toUpperCase' of undefined"

I was however able to right click on Dynamodb in the left hand nav, click refresh tables so I have connectivity but that refresh button within the System Diagram tool seems to have some issues.

![Screen Shot 2021-04-22 at 5 40 10 PM](https://user-images.githubusercontent.com/69162122/115801540-dab7dc00-a391-11eb-87e6-0ac72804df6d.png)

**Comment by bwship** [comment]
@ssnyder-sme - the issue was with how it was parsing the cloudwatch alarms.  We have a fix for this, and it will go out in the next release.

**Comment by ssnyder-sme** [comment]
Thank you!
