### ISSUE TITLE
Not able to see ECS clusters in different regions

### ISSUE THREAD

**Issue by ssnyder-sme** [commandeer/open#176]
When switching regions, I'm unable to see different clusters in different regions. Tried hitting the bit refresh button in the top left, but they don't show up. Tried hitting refresh in the ecs dashboard and got the attached screenshot error: "TypeError: Cannot assign to read only property 'message' of object". Right clicked refresh clusters on the ECS nav item, but it's unable to find the clusters. 

Could be related but maybe not, I'm on v1.8.1 and I know you were fixing some things for v1.9, but when i login and look at my account, the download link is still v1.8.1
![Screen Shot 2021-04-28 at 2 08 25 PM](https://user-images.githubusercontent.com/69162122/116472791-38817380-a82b-11eb-82d6-5541078c98a7.png)
![Screen Shot 2021-04-28 at 12 28 15 PM](https://user-images.githubusercontent.com/69162122/116472809-3b7c6400-a82b-11eb-9c56-451af513d396.png)

**Comment by bwship** [comment]
@ssnyder-sme - we didn't release 1.9 yet.  But we will investigate this.  You are seeing the clusters in one region, but not another?  Is that correct.

**Comment by ssnyder-sme** [comment]
Ah, i see, maybe that release will resolve it. 

For account 1 in us-east-1, I can see the ecs clusters. But for account 2, i have to switch to us-east-2 and then can't see clusters I expect to be there (that i can describe via cli using same creds). Seems like switch regions and hitting refresh isn't updating the cluster list. not that important because there isn't much you can do to the cluster in the app, but it'd be nice to see the resources

**Comment by bwship** [comment]
This has been resolved.
