### ISSUE TITLE
Localstack with SSL on doesn't seem to be compatible with Commandeer

### ISSUE THREAD

**Issue by jbentus** [commandeer/open#18]
Hello,

I have a localstack instance running in a docker container with USE_SSL=false and Commandeer seems to detect my S3 and SQS successfully.

However, when I start localstack with USE_SSL=true Commandeer shows **Network Failure** on all the services mentioned before. 

Kind regards,
Jose

**Comment by fsproru** [comment]
Hi @jbentus, thanks for reporting it. Supporting LocalStack over SSL should be pretty straightforward to implement. Just so we can help you better, would you mind answering a couple of questions:

1. Do you run LocalStack only on your computer locally and over SSL?
2. Do you run LocalStack on some remote host over SSL which you would like to connect from Commandeer?
3. Which use-cases are you developing for while using LocalStack with SSL enabled?

**Comment by jbentus** [comment]
Hi @fsproru. 

1. Yes.
2. No.
3. I am using Localstack mainly to debug/test my AWS apps which they run in production with SSL on. It would be good for us to keep/replicate an infrastructure as close as possible to how these apps will run in production. The .NET AWS SDK has SSL turned on by default and that also played a role on the current setup.

**Comment by animeshrisal** [comment]
Is it possible to connect to a localstack that is in a remote server ? There doesn't seem to be any option to change the ip address.

**Comment by fsproru** [comment]
@animeshrisal, we only support LocalStack running on localhost for now, that being said, running agains a remote host is a great feature to add.

**Comment by wkhatch** [comment]
> @animeshrisal, we only support LocalStack running on localhost for now, that being said, running agains a remote host is a great feature to add.

You should remove that claim then. It's pretty clearly stated in your info that you DO in fact support that feature, as of now...

**Comment by fsproru** [comment]
@wkhatch good call, this issue looks outdated since we now support both, the SSL connection and connecting to a remote host. Closing this for now. Let me know if you run into any issues.
