### ISSUE TITLE
Scrolling is broken all over the place

### ISSUE THREAD

**Issue by wkhatch** [commandeer/open#199]
In several areas of the stand alone application, scrolling is not working. Serverless Runner Terminal cannot scroll to see the last bits of an error stack trace, or any other output. Localstack dashboard scrolls as far as CloudTrail. Just two examples; there's a lot more.

**Comment by bwship** [comment]
@wkhatch - we are diving into this now.  Should have a build out with fixes for it in next couple days.

**Comment by bwship** [comment]
@wkhatch - version 2.2.1 has been pushed out that should fix the issue on LocalStack and Serverless Runner.

**Comment by bwship** [comment]
closing as these should be resolved
