### ISSUE TITLE
Commandeer ignores LOCALSTACK_API_KEY for LS Pro (mostly)

### ISSUE THREAD

**Issue by sfrooster** [commandeer/open#202]
I can get this to work, occasionally, but there is no rhyme or reason to how I do so. I run my own container out of docker-compose. I've set this as an environment variable in the localstack setup for this account. I have specified this key/value in the .env which docker-compose uses. I have been setting this env variable on the command line when I invoke docker-compose.

Again, occasionally I do *something* right and the commandeer UI recognizes this localstack setup as "Pro", but mostly it doesn't.

Definitely not how this should be working.

**Comment by sfrooster** [comment]
Are those fixes supposed to be available in 2.3.4, because they don't seem to be. I tried creating a new account by importing a running container (which starts just fine using docker-compose), two different ways - both started the container using docker-compose, one with a .env file and one with the env variables hard-coded into the docker-compose.yml. In neither case did commandeer pick-up the env variables. Even trying to manually start the imported container and entering the env variables into commandeer was not successful. It really does seem like commandeer is the piece having the issues.

**Comment by bwship** [comment]
In the account settings, for LocalStack, are you selecting the already
running container from the dropdown?

Cheers,
Bob Wall

(703) 919-3750

**Comment by sfrooster** [comment]
I did, yes. Between localstack, serverless (and the plug-ins) and
Commandeer, I really don't know where the problem lies. On Saturday evening
I managed through various machinations to use commandeer, a locally running
kafka cluster (running in its own docker containers via compose), and a
version of
https://github.com/commandeer/open/tree/development/sample-apps/serverless-localstack
which I modified, to get a lambda running locally (in
localstack/serverless, but deployed through commandeer) to use my kafka
cluster as it's source.

That has all since fallen apart and I can't recreate it, but that doesn't
surprise me since the first success felt like a minor miracle. Again, I
don't know where all the pain originates - commandeer, localstack,
serverless, or the integration of the three of them - but I've all but
decided this isn't a tenable workflow.

**Comment by bwship** [comment]
Yea, there does seem to be certain issues with LocalStack plus Serverless.
We had one team switch to using STS - https://serverless-stack.com/ which
means they basically only run stuff in the AWS ecosystem.  It basically
sets up a mocked web sockets environment for the Lambda's.  You can then
still use Commandeer with the access to AWS directly.

Cheers,
Bob Wall

(703) 919-3750
