### ISSUE TITLE
Use Lambda ClientContext in "invoke"?

### ISSUE THREAD

**Issue by QAnders** [commandeer/open#203]
I can't find a way to specify `ClientContext` with the local invoke command for a Lambda. We are using `ClientContext` to pass various "headers" to some of our Lambdas and I'd like to do the same in testing them through Commandeer. Possible?

**Comment by bwship** [comment]
@QAnders - Yea def possible.  We will add this in for the next release.  Hopefully we will get it out by end of this week.

**Comment by bwship** [comment]
Haha, moving at the speed of Serverless!

**Comment by QAnders** [comment]
We are just starting to look into Localstack and Commandeer as "development tools" as we are getting a more and more complex AWS environment and local testing is getting difficult with copy n' pasting event data between Lambdas and/or SQS events and such...
Was looking for a way to be able to handle it better and this farr Commandeer looks really awesome!

We just need to come to grips on how to "store" the Localstack container as we now run separate instances in different projects...

**Comment by bwship** [comment]
You can have multiple LocalStack instances running in Commandeer, with just different ports. Here is a doc about setting up multiple LocalStack accounts - https://docs.getcommandeer.com/docs/LocalStack/how-to-create-5-localstack-aws-environments-in-5-minutes-using-commandeer/ 

We have testers for DynamoDB Streams, SQS, API Gateway, and S3 too.  So you can do the invoke directly to Lambda or you can do the test where the actual event invoking it occurs.

**Comment by QAnders** [comment]
Nice! There's so many bells and whistles here so it'll take me some time sorting all out... 

One issue I've noticed is that we've run Serverless for a long time so some of our older AWS service dependencies are not added in serverless.yml, e.g. SQS queues or S3 Buckets but they have been added manually in S3 and then only the trigger/event has been added in serverless.yml...

Trying to add the resources in so they are created at deploy (for testing in Localstack/Commandeer) CloudFormation in AWS becomes very unhappy. SQS queues are not really a major issue as they are being cleared out but we have some S3 Buckets with loads of files in them that we can't re-create so need to figure that out...

**Comment by bwship** [comment]
@QAnders - just doing some final testing on this.  But we should have a release tomorrow with this.

<img width="1320" alt="context" src="https://user-images.githubusercontent.com/1326114/140173998-0aedb4fe-0633-4b61-974b-f455c61c0216.png">

**Comment by QAnders** [comment]
Awesome! Looks perfect!

**Comment by bwship** [comment]
@QAnders - this is out in the wild in version 2.3.5 - Let me know if you run into any issues.
