### ISSUE TITLE
Not able to edit localstack services ports

### ISSUE THREAD

**Issue by nakedcity** [commandeer/open#22]
I have not been abled to set different ports to the defaults when using localstack infrastructure. Is there any way to do it?

**Comment by fsproru** [comment]
Hi @nakedcity, good question. You should be able to specify a different port for LocalStack according to the configuration page here: https://github.com/localstack/localstack#configurations

Commandeer supports the default ports out of the box. The support for editing the ports will come in one of the future releases which you can see here: https://getcommandeer.com/docs/releases

**Comment by mircea-pop** [comment]
Is there a current way to edit the localstack ports for commandeer? maybe some config file?

**Comment by fsproru** [comment]
@mircea-pop @nakedcity editing LocalStack ports is available in the latest version of Commandeer. You should check it out.
