### ISSUE TITLE
HelloWorld State Machine Runner won't show in full screen

### ISSUE THREAD

**Issue by tomcatcher** [commandeer/open#228]
Hi,

I don't seem to find a way of viewing the HelloWorld State Machine Runner with all the details. Please see the screenshot attached.

Tom
![2022-04-09 (2)](https://user-images.githubusercontent.com/8667057/162576977-2a71f39a-4e18-4d6d-afa3-feb4c9d025d7.png)

**Comment by bwship** [comment]
@tomcatcher - this looks like a bug on windows with the scrollbar.  We are planning a release early next week, and will get a fix in for this as well.

**Comment by bwship** [comment]
@tomcatcher - We just released an update that has this fix in it in version 3.0.2.  If you close and reopen the app, you should have the newest version.  You can check the version by clicking the help icon in the top right of the home dashboard.
