### ISSUE TITLE
GUI Error on commandeer 1.9.5 on any "choose file" menu

### ISSUE THREAD

**Issue by markhsa** [commandeer/open#229]
When I am using commandeer version 1.9.5 on Fedora linux, and I click “choose file” in an area, I get gibberish (font?) on the screen.
I have attached a screen shot.

Let me know if you have any thoughts on the cause or a method of fixing it.

I have tried to find a solution but do not see any.
<img width="1413" alt="Screen Shot 2022-04-13 at 5 19 22 PM" src="https://user-images.githubusercontent.com/54253283/163285569-05fa86f2-9774-43fd-8df0-2e9ebdf084c4.png">

**Comment by bwship** [comment]
@[markhsa](https://github.com/markhsa) - please update to version 3.0.5.  You can download it from app.getcommandeer.com - If you are still having issues, let us know.
