### ISSUE TITLE
Can not detect docker

### ISSUE THREAD

**Issue by heowc** [commandeer/open#231]
I'm not using docker-desktop because I'm on a mac. So I am using [colima](https://github.com/abiosoft/colima).

For this reason, docker cannot be detected, and the localstack created with docker cannot be detected either. Is there any way to solve this?

- OS: Mac M1
- OS Version: 12.3.1 (Monterey)
- Commandeer Version: 3.0.4

**Comment by heowc** [comment]
I'm not sure if I did it right, but it doesn't seem to work properly. Even if I create an account, the sns and sqs I created with localstack are not visible. 🤔 

I think it would be great if you could change the docker.lock path. Is there any way to change this?

**Comment by heowc** [comment]
I solved this by creating a link file. Thank you.

**Comment by bwship** [comment]
Oh great.  Yea we will investigate better support of colima as well.
