### ISSUE TITLE
can't upload files to s3 bucket

### ISSUE THREAD

**Issue by mikestaub** [commandeer/open#26]
It throws an error. v0.3.4

**Comment by fsproru** [comment]
Hi @mikestaub could you send us the logs? You can access it from the debug menu.

**Comment by bwship** [comment]
@mikestaub - this could be an issue with your permissions with your access keys.  I have been uploading files successfully over the past few weeks.

**Comment by bwship** [comment]
Closing for now, as we haven't been able to reproduce on our end.  Let us know if this is still an issue for you though.
