### ISSUE TITLE
Add Account doesn't work for MacOS

### ISSUE THREAD

**Issue by staleks** [commandeer/open#28]
Hi,

I've just downloded version for MacOs (ver 0.3.5) added Profile info (Firstname, Lastname and email) but when I try to "+ Add Account" nothing pops-up.

I've tried from several places, top bar, dashboard, from "window top bar" Cmd + A, nothing.

Do you know maybe what I'm doing wrong?

By the way, my MacOS is Catalina 10.15.1.

**Comment by bwship** [comment]
Are you on version 0.3.5?  Have you been using Commandeer prior to version 0.3?  We did have a tweak in the account management, but I haven't seen this issue before.  If you navigate to ~/Library/Application Support/Commandeer/data you should see an accounts folder.  If you only have the local in there, you should see a json file.  One hacky way to fix it, is to copy that file, and save it with a new GUID, like account.NEW_GUID.json and then change the isLocal to false in there, and if you refresh the app, it should appear in your dropdown.

**Comment by staleks** [comment]
Hi Bob,

no, this is my first use of Comandeer. To be honest I was looking at MadeWithVueJS page and saw your product there. I'm actively using AWS so I find that it might be helpful to me.

I'll update you here with findings in my local file system.

**Comment by staleks** [comment]
This screenshot from logs can maybe help?

<img width="1193" alt="Screenshot 2019-12-09 at 19 51 06" src="https://user-images.githubusercontent.com/1543466/70463575-6abaf580-1abd-11ea-874e-b8cb115bb17d.png">

**Comment by bwship** [comment]
Ok, create that accounts folder and it should start working.  We will get a
hotfix out for this very soon.  Thank you so much for reporting it.

**Comment by staleks** [comment]
Yes ... this helped.
<img width="1201" alt="Screenshot 2019-12-09 at 19 57 24" src="https://user-images.githubusercontent.com/1543466/70463960-35fb6e00-1abe-11ea-80e7-39702fcbb40d.png">

**Comment by staleks** [comment]
Hopefully, the next release will have everything working "out of the box".

For me, this workaround did a job. Closing the ticket.

**Comment by bwship** [comment]
Yes sir.  This was a bug introduced in that last version just for new users.  Current users were not affected.  We got the fix out last night.  Sorry about that.
