### ISSUE TITLE
Blog posts aren't dated

### ISSUE THREAD

**Issue by mwgamble** [commandeer/open#29]
I don't think this is the right place to mention this, but I wasn't sure where else to do so. None of the blog posts on the Commandeer website have dates on them, making it difficult to determine if the information is potentially out of date (amongst other things).

**Comment by bwship** [comment]
Hi, we actually have a slight bug on the getcommandeer.com/blog section of the site that it isn't rendering correctly.  They all do have dates on them. I am guessing you might be referring to our docs section at getcommandeer.com/docs  which do not have dates.  All of those should be up to date, except for the getting started section.  We are working on a better onboarding experience, and will update that doc then.

**Comment by mwgamble** [comment]
This blog post doesn't have a date on it:

https://getcommandeer.com/blog/install-localstack

**Comment by bwship** [comment]
Yea, we will add a date to that one. Thanks for the heads up.  It should be current in terms of how to install localstack.  If you do have any issues with getting it setup, you can head over to localstack.cloud as they have great setup instructions on their github repo as well.
