### ISSUE TITLE
Sqs Message Body Serialization

### ISSUE THREAD

**Issue by rv-amadden** [commandeer/open#39]
Messages added to queues are serialized twice. 

| input  | expected  | actual |
|:-:|---|---|
|  { "hello": "world" } | "{ \"hello\": \"world\" }"  | "\"{ \\\"hello\\\": \\\"world\\\" }\""  |

A nice to have would be the ability to select a message body type,`text` ,`json` , etc because I find myself sending both stringified and raw payloads.

**Comment by bwship** [comment]
@rv-amadden - thanks for raising the issue.  We will look into it.  I like the idea of selecting the body type.

**Comment by bwship** [comment]
You can now toggle between json or plain text.

<img width="722" alt="json" src="https://user-images.githubusercontent.com/1326114/102107263-8c9d3580-3dff-11eb-9b0d-27fd94909868.png">

**Comment by bwship** [comment]
this will go out in version 1.6

**Comment by bwship** [comment]
Released in version 1.6
