### ISSUE TITLE
Feature Request: Ability to Assume Role

### ISSUE THREAD

**Issue by c1moore** [commandeer/open#43]
It would be great to be able to assume roles within Commandeer when connecting to AWS accounts.

**Comment by fsproru** [comment]
Thanks @c1moore, that’s a great feature which is on our roadmap 👍

**Comment by c1moore** [comment]
Awesome. Do you have an ETR for this feature?

**Comment by fsproru** [comment]
We don’t have the exact ETA unfortunately. That being said it’s definitely
on our radar, so as the SSO. Let’s keep this issue open and we’ll post here
once assume role is supported.

**Comment by bwship** [comment]
@c1moore - I wanted to get your input on how you envision this working.  I am starting to frame it out a bit, and have some thoughts on it too.  But wanted to see what you were thinking.

**Comment by jaridmargolin** [comment]
Without assume role, are there any recommended approaches to working with commandeer in a multi account org? I guess I would just need to create IAM users in each account?

**Comment by bwship** [comment]
@jaridmargolin - Yea, what you can do is inside Commandeer, you can create multiple accounts, and each of those can have different keys that you are using.  Then you can switch between accounts easily, and if each account has a different default region selected, it remembers that as well when switching.

**Comment by AnakinPt** [comment]
Without this option, for me this app is totally useless. I can't create IAM users just for me to connect using an app.

**Comment by bwship** [comment]
This is currently in progress.  We have the role selection in the top nav working, and the retrieving of the short lived keys.  Tying it all together now and it should be out in the next week or so.  

<img width="1319" alt="assume-role-capability" src="https://user-images.githubusercontent.com/1326114/154740913-07fa6ba6-1f17-40f9-9632-aa4c3f162ded.png">

**Comment by bwship** [comment]
@AnakinPt @jaridmargolin @c1moore - this feature is now live in version 2.5.0!
