### ISSUE TITLE
S3 objects do not populate in dashboard

### ISSUE THREAD

**Issue by OskergMonReap** [commandeer/open#46]
**Commandeer version**: 0.6.0
Installed across multiple Linux Distro's via **AppImage**
**Localstack version**: 0.10.8 [started via `localstack start` command]
**Further details**: all testing has been done using awscli-local to interact with localstack

**Issue**: Only resources, ie S3 buckets, are populating within the Commandeer dashboard. When I add objects via the awslocal commands to interact with localstack, the files never show up within the dashboard

**Expected**: To see files and "folder" structures added from cli to the bucket within the Commandeer dashboard

**Comment by fsproru** [comment]
Hi Travis, thanks for submitting the issue, wound you mind sending us the
exact commands you ran and your local account file located in the data
folder (it’s in top right help menu in Commandeer app)?

**Comment by OskergMonReap** [comment]
Thanks for the quick response! Account file details are below:
```
{
    "isLocal":true,
    "isProduction":false,
    "id":"63fdc0b7-ecb2-4eef-9988-92a1121dae5e",
    "name":"local",
    "algolia":{"applicationId":"","apiKey":""},
    "aws":{
        "region":"us-east-1",
        "accessKeyId":"NO_LOCAL_ACCESS_KEY_ID",
        "secretAccessKey":"NO_LOCAL_SECRET_ACCESS_KEY",
        "apigatewayEndpoint":"http://localhost:4567",
        "cloudwatchEndpoint":"http://localhost:4582",
        "cloudwatchLogsEndpoint":"http://localhost:4586",
        "cloudwatchEventsEndpoint":"http://localhost:4587",
        "dynamoEndpoint":"http://localhost:4569",
        "ec2Endpoint":"http://localhost:4597",
        "iamEndpoint":"http://localhost:4593",
        "lambdaEndpoint":"http://localhost:4574",
        "s3Endpoint":"http://localhost:4572",
        "s3Prefix":"",
        "snsEndpoint":"http://localhost:4575",
        "sqsEndpoint":"http://localhost:4576"
    },
    "database"{
        "host":"",
        "initialDatabase":"",
        "username":"",
        "password":"",
        "type":"POSTGRES"
    },
    "slack":{"token":""}
}
```

Bucket was created via: `awslocal s3 mb s3://<bucket-name>`
--> verified it was succesfully created via dashboard as well as `awslocal s3 ls` and `awslocal s3api list-buckets` commands

Files/Objects were added via `awslocal s3 cp <file> s3://<bucket-name>/`
--> verified object was succesfully added via `awslocal s3 ls s3://<bucket-name>/` and `awslocal s3api list-objects --bucket <bucket-name>` as well as the `list-objects-v2` command with same structure

Unfortunately, only the bucket shows up in the Commandeer dashboard, all objects added via aws cli (awslocal in this case since i'm using localstack) are never detected and populate.

**Comment by wkhatch** [comment]
I'm experiencing this issue as well. The walk through here: https://docs.getcommandeer.com/blog/localstack/how-to-view-files-on-s3-in-localstack.html is not what I experience. I get blank panels that indicate the Port only, for all Localstack resources. I am running mine in context of a docker-compose, where ports are mapped between host and the container, so I am seeing the running services in Commandeer. I'm also on the latest version of localstack, and using the single port config as the old endpoints method is deprecated and no longer available in this version.

**Comment by fsproru** [comment]
@OskergMonReap, would you mind upgrading to the latest version of Commandeer which has the refresh button next to the account select drop down. See if clicking it helps to see the new content created outside of Commandeer so. We fixed a similar issue in one of our releases since 0.6.0.

**Comment by fsproru** [comment]
@wkhatch would you mind sharing your Docker Compose file and the way you create resources so we can reproduce the issue locally?

**Comment by wkhatch** [comment]
@fsproru I subsequently figured out my issue. I had been digging into the views from the Localstack tab, and not the actual corresponding aws service tabs. And, the way that behaves based on local/production accounts also added to my own confusion a little. But, everything works, and, had been working. I'm assuming that commandeer automatically connected to my localstack container instance via docker, and not because the port ranges are mapped to my localhost, correct? I have to say, this is far better than localstack's own UI, imo. Very nice, and apologies for my newbie ness. I'd only suggest maybe rethinking the views you do arrive at when digging in through the Localstack tab; they're not very informative or useful as is. Probably a lot more you could do there beyond just displaying the port it's running on, but not a big problem or anything. Thanks!

**Comment by OskergMonReap** [comment]
> @OskergMonReap, would you mind upgrading to the latest version of Commandeer which has the refresh button next to the account select drop down. See if clicking it helps to see the new content created outside of Commandeer so. We fixed a similar issue in one of our releases since 0.6.0.

Just installed the newest version and my issue is resolved, I'm able to view folder structure and objects successfully. Thanks @fsproru, let me know if you would like me to keep this issue open to continue troubleshooting with @wkhatch

**Comment by OskergMonReap** [comment]
Glad its working for you @wkhatch, @fsproru perhaps a link to the S3 service tab from the localstack's s3 tab would be a nice feature that would minimize confusion? regardless, all is well. closing

**Comment by fsproru** [comment]
Thanks guys, linking into a corresponding AWS service from a LocalStack detail page is actually a great idea. Well look into that.
