### ISSUE TITLE
Mac: Uploading credentials.csv through drag&drop doesn't work

### ISSUE THREAD

**Issue by marc-guenther** [commandeer/open#52]
Dragging the credentials.csv file makes it apper, but the button just stays grey. I had to enter the two Keys manually

**Comment by bwship** [comment]
this is working for me on the current version and new version.  I'll keep it open for now to monitor it.

**Comment by marc-guenther** [comment]
Ok, now I cannot reproduce that anymore. Drag'n drop works correctly all the time.

What doesn't work though is clicking the Upload button. It works exactly once, when after the first upload you remove the file and the keys in the two textfields, another upload will not add the file anymore. It will open the File Open Dialog, but not do anything with the selected file.

I also cannot reproduce the behaviour anymore, that a file is shown, but the "Test Connection" button is still gray. I don't remember if there were entries in the two textfield in that state.

**Comment by bwship** [comment]
ok no problem.  we will look into the upload button.  we have been doing some cleanup in there anywya, and are looking into some sort of ability to upload from your ./aws folder too
