### ISSUE TITLE
Navigation column: Selecting an entry sometimes doesn't work

### ISSUE THREAD

**Issue by marc-guenther** [commandeer/open#53]
In the Navigation column, mouse-down on the text of an unselected entry, move the mouse over to the icon, and release.

This will select the entry, but not switch the corresponding view.

I only noticed, apparently I like to click in the area between icon and text, and then if you move the mouse just a little bit while clicking, this happens.

**Comment by bwship** [comment]
will monitor this with our new setup on navigation.

**Comment by fsproru** [comment]
Good once, I increased the clickable area in the new nav, so it should be
better in the next release.

**Comment by marc-guenther** [comment]
This bug works in both directions, if you start at the icon and drag over to the text, and vice versa...
It seems the icon and text are two different things, and can't handle each others events?

**Comment by fsproru** [comment]
Yep, both, the icon and the text have their click area. We tightened up the
navigation in this upcoming release, let’s see how it feels in the new
release.
