### ISSUE TITLE
Navigation column: expandable entries do not get selected

### ISSUE THREAD

**Issue by marc-guenther** [commandeer/open#54]
Clicking on an entry with children:
- toggles the children on and off
- select the corresponding view (if it has one, some entries don't have one)
- but does NOT select the entry itself. The selection just stays wherever it was.

Eg. I'm in the "Whats New" entry, and click on "API Gateway".

It's also not a good idea to have the same click to the toggling AND the selecting.

**Comment by bwship** [comment]
In next release, the parent in the treeview wont cause you to change pages.  If there is a dashboard, it will be a menu item under say API Gateway.  I think this flow works better, but we shall see.   Next release is slated for this week.

**Comment by marc-guenther** [comment]
Yes, that sounds good. I was wondering, why some topics have Dashboards, and some don't. It makes sense to make a Dashboard for every one. Parent items shouldn't have pages at all.
