### ISSUE TITLE
LocalStack Install button is disabled

### ISSUE THREAD

**Issue by marc-guenther** [commandeer/open#56]
Ok, this may be a minor detail. But the first time I played around with this, the "Install" button was gray, and the "Docker Container >" button next to it doesn't do anything.

Turns out I pressed the Play button. This complains that it cannot start LocalStack (obiously, as  I don't have it installed), but it also disables the Install button, and never recovers from that situation.

Restarting Commandeer enables the button again.

**Comment by fsproru** [comment]
Hi @marc-guenther, thanks for reporting it. Would you mind trying the latest version of Commandeer?

We removed the install button and starting LocalStack pulls a LocalStack container automatically. Just make sure you have Docker installed.

Closing this one for now. Let us know if you run into any issues and we'll reopen.
