### ISSUE TITLE
Reload results in white empty window sometimes

### ISSUE THREAD

**Issue by marc-guenther** [commandeer/open#57]
I have not yet been able to reproduce this reliably, but it happened so often now, that I wanted to report it. After I use Commandeer for a while, pressing _Reload_ (CMD-r) simply clears the window forever. Also _Force Reload_ doesn't make anything reappear.

Opening a new window still works.

**Comment by bwship** [comment]
I believe this is resolved for the next release.  I know that it will at least now give you a nice but i believe it also doesn't hang anymore.

![comm](https://user-images.githubusercontent.com/1326114/78102170-83b62200-739e-11ea-84f0-a8f878a397c1.png)

Going to close for now.
