### ISSUE TITLE
Filter in DynamoDB is broken

### ISSUE THREAD

**Issue by ssanri** [commandeer/open#62]
In documentation it mentions that table can be filtered quickly with indexed fields which seems to not work at all. Searching primary column or any indexed column value doesn't return any results. Also why id column is default in grid? I haven't understand this from 4-5 versions back. For instance as policy we are not allowed to use generic column names, each table should have identifier with it's name. userId, roleId etc. If commandeer can generate other columns from schema why there is also an id column in every table?

**Comment by fsproru** [comment]
Hi @ssanri, thanks for reporting an issue with the search, well look into it.

Regarding the column names, you can customize the field names to fit your usecase.

**Comment by ssanri** [comment]
@fsproru Thanks for the response. Yeah I can create  and customize the field names but can't get rid of id column created by default. Also it would be really nice and great feature if we can define which columns to be displayed in table view.

**Comment by fsproru** [comment]
Nice! The ability to show and hide the columns is a good one to add.

I see what you're saying now. The id column is still displayed by default
for a table with a primary key other than id (like userId, etc). Good
catch, we'll take a look 👍

**Comment by bwship** [comment]
@ssanri - the id column was hard coded if there were no records.  We have made a fix for this.  It will be out in the next week or so with the new release.  We also added the ability to truncate a table, and refined the uploading capabilities.  I am going to look into the filtering aspect now, to try to make sure that is working.  Thanks for the feedback.

**Comment by ssanri** [comment]
of course. thanks for the consideration. also I am a UI/UX engineer and I have a quick feedback as a user. The new right information sidebar you guys added enormously big and taking unnecessary real-estate.

![image](https://user-images.githubusercontent.com/53793378/81308073-60daf580-904f-11ea-8417-f642fe3918c9.png)

since we can't resize any block vertically I can only see small part of table. For instance in my user table I have plenty of columns and rows, so I can't really see the horizontal scrollbar at the bottom,  So if I need to see firstName of the first column patient, I have to scroll all the way to bottom of the screen, then scroll left a little, 

![image](https://user-images.githubusercontent.com/53793378/81308378-b44d4380-904f-11ea-939e-fdcf05eb4a44.png)

but now I don't have the column headers, now I need to go all the way up and see if column is there

![image](https://user-images.githubusercontent.com/53793378/81308606-faa2a280-904f-11ea-8247-27b22e920700.png)

nope, scroll all the way down, move a little more, then scroll up... and this goes on until I find the column name. 

I think it makes more sense to remove overflowing in table-body and have table container to fill space with overflow auto.  this way scrollbars and headers will be always visible. Another option might be making table headers fixed or floating  so scrolling in container would not change the position of table header.

**Comment by fsproru** [comment]
@ssanri, great feedback! We’re improving this layout altogether, I like your suggestions. If you have more feedback, don’t hesitate to reach out.

**Comment by bwship** [comment]
@ssanri - The plan is to have a dashboard page and a data page for each table.  This should make it a much better experience.  We are hoping to get the new layout out in the next week or so.

**Comment by bwship** [comment]
@ssanri - closing this one out too.  Filtering should be solid, though in version 1.4 we should have multi-filter and an actual run button.
