### ISSUE TITLE
Pagination and refresh issues

### ISSUE THREAD

**Issue by ssanri** [commandeer/open#64]
I am not sure if this one already has been reported but if I change the pagination per page count from 10 to 25 and open one record, closing window behaves a weird way. pagination count still shows 25 but list only shows first 10. Same thing also happens if I move through pages. i.e opening a record on page 5 then closing takes you back to page 1 but pagination still shows page 5. 

Another issue arise after last update is refresh functionality. in any table if I click on refresh everything disappears. just blank page. then I go back to dynamodb dashboard, find table and reload.  

Refresh Issue
![image](https://user-images.githubusercontent.com/53793378/82720292-29d82700-9c80-11ea-9cbc-9cec67f8ef9b.png)

![image](https://user-images.githubusercontent.com/53793378/82720294-3492bc00-9c80-11ea-8f60-c69d0507984b.png)

Pagination issue

![image](https://user-images.githubusercontent.com/53793378/82720310-5f7d1000-9c80-11ea-8bc3-228173fd9dae.png)

![image](https://user-images.githubusercontent.com/53793378/82720315-6f94ef80-9c80-11ea-93e2-aa01fdca3cf6.png)

![image](https://user-images.githubusercontent.com/53793378/82720319-863b4680-9c80-11ea-81e6-033af3fdab34.png)

![image](https://user-images.githubusercontent.com/53793378/82720329-a539d880-9c80-11ea-946e-de4102d6ece7.png)

![image](https://user-images.githubusercontent.com/53793378/82720346-c4386a80-9c80-11ea-857d-825150993686.png)

**Comment by fsproru** [comment]
Thanks @ssanri. @elgar999, could you take care of this pagination issue while you’re working on DynamoDB?

**Comment by elgar999** [comment]
@fsproru, sure

**Comment by bwship** [comment]
@ssanri - the fixes for this are coming out in the next week or so in version 1.3.  There are an absolute ton of enhancements to Dynamo, so I think you will really like it.

**Comment by bwship** [comment]
@ssanri - closing this one.  Let us know how your experience goes on Dynamo in version 1.3.  We are planning on releasing some more enhanced filtering capabilities, so any input would be helpful.
