### ISSUE TITLE
Total Messages are getting concatenated under SQS Dashboard instead of their sum

### ISSUE THREAD

**Issue by pankajazy** [commandeer/open#65]
![image](https://user-images.githubusercontent.com/30962971/83605921-636d3400-a596-11ea-86ae-a6d9173fdf4c.png)
There are 2 sqs queue : sms_queue (12 messages) and smsqueue (1 message)
On the dashboard total Messages count should be 13 instead of 121 .

**Comment by fsproru** [comment]
Thanks @pankajazy, good catch 👍

**Comment by fsproru** [comment]
This one should be fixed in 1.2.0
