### ISSUE TITLE
Caching of resources won't refresh

### ISSUE THREAD

**Issue by mengelseatz** [commandeer/open#72]
I'm running the latest Commandeer on Mac OS.    When I boot up Localstack and generate resources from a CloudFormation template, I can hit refresh at the account level and in my AWS dashboard the resources are correctly there.   But if I change my template to say remove 90% of the resources and redeploy my Localstack container and hit refresh in Commandeer all the old resources (DDB tables, s3 buckets, etc) that I removed from the CloudFormation template are still there.. They also persist between restarts of Commandeer making development against Localstack mostly unusable.  The only way I can find to get around this is to go into my ~/Library/ApplicationSupport and remove the whole Commandeer directory which forces me to setup accounts all over, rewire the ports to use the EDGE_PORT to 4566 in all the AWS resource configurations at the AWS level (shouldn't this be the default for local BTW?).

**Comment by bwship** [comment]
Couple different things on this.  Instead of removing the whole Commandeer folder, you can just remove the ~/Library/ApplicationSupport/data/services-cache folder, and then hit refresh and it should be correct.  The services-cache folder is just json representation of your system stored locally.  

But this of course isn't an ideal solution.  I am wondering if the resources in your localstack are persisting on the docker volume.  To figure that part out, try to do the first part, remove the services-cache folder, and let me know if they are still there after you do your deploy, and we can help debug it further.

**Comment by mengelseatz** [comment]
Thanks @bwship    Let me play around in and see if I can get this cleared up. 

Appreciated the quick response.

**Comment by mengelseatz** [comment]
OK that helped.. I also removed any traces of storing data on the container.   That said, there's still a lot of having to hit refresh multiple times to get it updated as the global refresh doesn't  seem to send events down to the individual service views in the sidebar or the detail panes on the right side.    I get that in prod this isn't likely to be the case but when doing new development where you're building out a bunch of services and testing various scenarios it's a lot of hitting refresh :)

**Comment by bwship** [comment]
@mengelseatz - yea, two things on that.  1. The upcoming release 1.3 will have better refreshing at the service level.  We are actually working through some major pieces now for tighter flow integration of the side navigation, breadcrumbs, and right-click menus, so as a result this is getting cleaned up too.  2. we have been discussing making a cloud formation runner, like how we have for Ansible and Serverless, that would let you run your cloud formation directly form our GUI, which we think will help the overall workflow.  

Any suggestions you have, let us know, as we are working to make this tool as useable as possible.  Appreciate the input.

**Comment by mengelseatz** [comment]
Thanks @bwship those all sound good.   Right now I'm working on a local only dev solution for the teams to use and  having a way to push the CloudFormation into the app I think would be useful and easier to grok as I wouldn't have to have these init scripts running in the local stack container.   Also they could test it against an AWS sandbox as well which I like the idea of.     I'm not giving up - just reporting my experience.   I think this tool has a ton of promise!
