### ISSUE TITLE
Cannot add variables when using Ansible runner

### ISSUE THREAD

**Issue by mklatsky** [commandeer/open#77]
Commandeer version: 1.3.0
OS Version: MacOS 10.15.5 (19F101)

When using the Ansible runner, I need to add an environmental variable for my playbook.
 When I click the gear icon, I am presented with the Ansible Settings window. When I click the "+ Add" button, beyond the animation- nothing occurs. Thus, I am unable to add the needed environmental variables.

Expected behavior:  clicking the "+ Add" button should then allow me to add a key and a value.

**Comment by fsproru** [comment]
Hi @mklatsky, thanks for reporting the issue. Could you send us the content of your account file from your data folder (with the sensitive information removed). You can access it from the Help menu at the top right. Perhaps the Ansible section of the account needs a minor adjustment.

**Comment by mklatsky** [comment]
[commandeer.json.txt](https://github.com/commandeer/open/files/5226923/commandeer.json.txt)

I have attached my obuscated account file. Interestingly, I am not seeing an Ansible section. Thank you.

**Comment by fsproru** [comment]
Thanks @mklatsky, we found the issue and the fix will come out in the next release. In the meantime you can add the Ansible section to your account file at the root level to start saving the variables from the UI.

```
  "ansible": {
    "id": "a4cce4e7-6c4d-4676-ba86-7385041b95ee",
    "variables": [
      {
        "id": "3256b418-bd00-4233-8029-09829d1755fd",
        "key": "TEST",
        "value": "VALUE"
      },
      {
        "id": "490a4955-5ac1-43d9-9881-4257e600e2e7",
        "key": "TEST",
        "value": "VALUE2"
      },
      {
        "id": "0780d6d3-52c8-40de-b120-ad7ffd03d7f6",
        "key": "TEST3",
        "value": "VALUE3"
      }
    ],
    "environmentVariables": []
  },
```
