### ISSUE TITLE
View Data text selectable 

### ISSUE THREAD

**Issue by wkhatch** [commandeer/open#78]
In both lambda invocation logs, and cloudwatch logs, it would be nice if the displayed text were selectable for clipboard copy, etc.

**Comment by fsproru** [comment]
Thanks @wkhatch, it's a good idea to add it to the table view. Did you try switching to the terminal view and copy the text from there?

**Comment by bwship** [comment]
@wkhatch - adding in a modal for each row in both locations.  That will let you select the row, inspect the information, and share or copy the data.  I'll update this card with a screenshot of it when it gets further along, but it will go out in the 1.6 reelase.

**Comment by bwship** [comment]
Released in version 1.6
