### ISSUE TITLE
Pagination issue resurrected

### ISSUE THREAD

**Issue by ssanri** [commandeer/open#81]
Hi, I have reported this while back and it looks like it is resurrected. On dynamodb table data, changing pagination options or page doesn't reflect on table. For instance initially it loads 10 records of 20. I can see 10/20 at the bottom. if I change to second page, page number changes but data is still the same on the table. 

If I reopen the same page then change 10 per page to 20/50 per page, table still shows only 10 records.

**Comment by fsproru** [comment]
Hi @ssanri, thanks for reporting it. We're reworking the pagination, as well as the query and filter capability. It's coming out soon in the new 1.5 release.

**Comment by ssanri** [comment]
Hi @fsproru, Is there any updates on rework of pagination? Currently it is really makes it hard to use since I can only use one filter on tables and when there are 300 results I can only see first 10 of them.

**Comment by fsproru** [comment]
Yep, the rework is in progress, we're aiming for doing a release this week.

**Comment by fsproru** [comment]
@ssanri the new version 1.5 is out with the new Dynamo query experience. Let us know if you run into any issues.

**Comment by ssanri** [comment]
Perfect! thank you Alex. Works as expected. One quick feedback, unrelated, we would love to apply format/unformat data option on json data fields too. when there is large amount of json data in one field, rows become huge and hard to track/compare in a table view. That would be amazing to switch off Format Data option and flatten & truncate json fields to give a better visual table.
![image](https://user-images.githubusercontent.com/53793378/100534099-9016a700-31d9-11eb-89ae-ca4005970ba7.png)

**Comment by fsproru** [comment]
Thanks @ssanri, we actually have a similar solution in our log viewer, if
there is some large json or text in a column, we add a button that shows
the whole column on click. I like your suggestion to just visually truncate
the long values in the table, because you can see the whole data when
clicking on the row. Good one! Added it to the list. Please don't hesitate
to share more feedback, it's been very helpful.
