### ISSUE TITLE
Localstack not picking up correct region

### ISSUE THREAD

**Issue by bwship** [commandeer/open#86]
If you switched to a local account, it does not use the correct region.

**Comment by smacdav** [comment]
The value of the environment variable DEFAULT_REGION is us-gov-west-1. My terraform file (which also specifies us-gov-west-1) and command line output are in the attached zip file. Note that the FunctionArn contains us-east-1 as the region.

[wrong-region.zip](https://github.com/commandeer/open/files/5654123/wrong-region.zip)

**Comment by fsproru** [comment]
@smacdav, thanks for sharing the example. We made a fix in the 1.5.2 release we just pushed out. Now the `DEFAULT_REGION` environment variable (or any other environment variable) gets passed in to LocalStack on start.

I just started LocalStack with `DEFAULT_REGION` set to `us-gov-west-1`, then ran through your example (had to create a dummyHandler.zip file with an empty java file in there to have it deployed) and the lambda gets listed in `us-gov-west-1` now.

[wrong-region-with-dummy-handler.zip](https://github.com/commandeer/open/files/5655724/wrong-region-with-dummy-handler.zip)

```
awslocal lambda list-functions
{
    "Functions": [
        {
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "Version": "$LATEST",
            "CodeSha256": "G1pto1PIQPEcOZyj8bbLhkyT575oIltMWT1KQBNbi60=",
            "FunctionName": "lambda_local_spring_boot_test",
            "VpcConfig": {},
            "LastUpdateStatus": "Successful",
            "MemorySize": 3000,
            "RevisionId": "630a39b4-321f-4934-8aab-da768a58bfd6",
            "CodeSize": 184,
            "FunctionArn": "arn:aws:lambda:us-gov-west-1:000000000000:function:lambda_local_spring_boot_test",
            "State": "Active",
            "Handler": "com.example.localspringbootlocalstackpractice.Handler::handleRequest",
            "Role": "arn:aws:iam::000000000000:role/iam_for_spring_boot_test_lambda",
            "Timeout": 900,
            "LastModified": "2020-12-07T22:56:35.628+0000",
            "Runtime": "java8",
            "Description": ""
        }
    ]
}
```

Let us know if the latest 1.5.2 works for you.

**Comment by smacdav** [comment]
Thank you, Alex. This is my personal email, but I'll give your fix a try tomorrow morning.

Scott

**Comment by fsproru** [comment]
Tested and works, closing the issue
