### ISSUE TITLE
DynamoDB: Weird list of tables

### ISSUE THREAD

**Issue by ssanri** [commandeer/open#88]
When something goes wrong, and application restarted. All table names displays as last table had issue. Please see screenshot below 

![image](https://user-images.githubusercontent.com/53793378/101503695-5ca5ec00-3940-11eb-8d69-d0544ca7b731.png)
![image](https://user-images.githubusercontent.com/53793378/101503777-77786080-3940-11eb-9a62-ead438a151e4.png)

**Comment by bwship** [comment]
@ssanri - as afirst step, on the account page (if you click the arrow in the top toolbar next to the current account and region dropdown), and press the clear local cache, and then hit the refresh button.  Might have just been something funky.  We will investigate further though.

**Comment by ssanri** [comment]
Yes even reloading the app fixes the issue showing correct tables in list. I just wanted to report the bug I am seeing on initial load. Also on the side note, it is not just the names, all items on the list indeed opens same table. I was able to open few of them and removed some rows, all others were also in sync with the action taken.

**Comment by fsproru** [comment]
@ssanri does it happen when the table fails to truncate due to the filters being set like in #89? Did you do anything specific that led to displaying multiple tables in the side nav?

**Comment by ssanri** [comment]
@fsproru That's correct. It happens in both cases when something fails in dynamodb action, and reopen the app after closing. Also not only sidebar list. DynamoDB dashboard items as well as size chart on top also displays same table as the count of actual tables in system. I have 31 tables in dynamo and I can see 31 websocket-local table in both sides.

**Comment by fsproru** [comment]
Got it, then solving the failure should take care of this issue with duplicated tables. We'll look into it. Thank you.

In the meantime, you can use the clear cache button on the account page. And for the table truncation, resetting the search filter before truncating a table is a good workaround in the meantime.

**Comment by bwship** [comment]
Released in version 1.6
