### ISSUE TITLE
DynamoDB: Truncate fails when pk and sk defined together

### ISSUE THREAD

**Issue by ssanri** [commandeer/open#89]
When there is partition key and sort key defined in a table Truncate operation fails

![image](https://user-images.githubusercontent.com/53793378/101504148-e2299c00-3940-11eb-8e04-41c117aa4dbb.png)

![image](https://user-images.githubusercontent.com/53793378/101504213-f372a880-3940-11eb-942b-70c07e75295f.png)

**Comment by fsproru** [comment]
That's a good one. Thanks @ssanri, I can take care of this one.

**Comment by bwship** [comment]
@ssanri  - this is fixed and will go out in the next release

**Comment by bwship** [comment]
Released in version 1.6
